version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: src/Wowthing.Backend/development.Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BattleNet__ClientID: $BattleNet__ClientID
      BattleNet__ClientSecret: $BattleNet__ClientSecret
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    networks:
      - wowthing
    volumes:
      - ./:/app/

  frontend:
    build:
      context: .
      dockerfile: frontend/development.Dockerfile
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    networks:
      - wowthing
    volumes:
      - ./:/app/
      - frontend-cache:/root/.cache
      - frontend-dist:/app/src/Wowthing.Web/wwwroot/dist/
      - frontend-nm:/app/frontend/node_modules/

  web:
    build:
      context: .
      dockerfile: src/Wowthing.Web/development.Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BattleNet__ClientID: $BattleNet__ClientID
      BattleNet__ClientSecret: $BattleNet__ClientSecret
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    networks:
      - wowthing
    ports:
      - "55500:5000"
      - "55501:5001"
    volumes:
      - ./:/app/
      - frontend-dist:/app/src/Wowthing.Web/wwwroot/dist/

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: wowthing
    networks:
      - wowthing
    ports:
      - "55532:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - wowthing
    ports:
      - "55579:6379"
    restart: always
    volumes:
      - redis:/data

networks:
  wowthing:

volumes:
  frontend-cache:
  frontend-dist:
  frontend-nm:
  postgres:
  redis:
