version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: src/Wowthing.Backend/development.Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BattleNet__ClientID: $BattleNet__ClientID
      BattleNet__ClientSecret: $BattleNet__ClientSecret
    networks:
      - wowthing
    volumes:
      - ./:/app/

  web:
    build:
      context: .
      dockerfile: src/Wowthing.Web/development.Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BattleNet__ClientID: $BattleNet__ClientID
      BattleNet__ClientSecret: $BattleNet__ClientSecret
    networks:
      - wowthing
    ports:
      - "55500:5000"
    volumes:
      - ./:/app/

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: wowthing
    networks:
      - wowthing
    ports:
      - "55532:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - wowthing
    ports:
      - "55579:6379"
    restart: always
    volumes:
      - redis:/data

networks:
  wowthing:

volumes:
  postgres:
  redis:
