version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: wowthing
    networks:
      - wowthing
    ports:
      - "55532:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - wowthing
    ports:
      - "55579:6379"
    restart: always
    volumes:
      - redis:/data

  web:
    build:
      context: ./src/Wowthing.Web
      dockerfile: development.Dockerfile
    depends_on:
      - postgres
      - redis
    networks:
      - wowthing
    ports:
      - "55500:5000"
    volumes:
      - ./:/app/

networks:
  wowthing:

volumes:
  postgres:
  redis:
