.build:
  stage: build
  only:
    refs:
      - main
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from "$CI_REGISTRY_IMAGE/$IMAGE_NAME:latest" --tag "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" --tag "$CI_REGISTRY_IMAGE/$IMAGE_NAME:latest" --file "$DOCKER_FILE" .
    - docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME:latest"
