name: Continuous Integration

on: [pull_request, workflow_dispatch]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        id: cache-yarn
        with:
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-nodenodemodules-
          path: |
            node_modules

      - name: Install dependencies
        working-directory: frontend/
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: ESLint
        working-directory: frontend/
        run: yarn run lint

      - name: Svelte Check
        working-directory: frontend/
        run: yarn run check
