name: Build and deploy web

on:
  push:
    branches:
      - main
    paths:
      - 'src/Wowthing.Lib/*'
      - 'src/Wowthing.Web/*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: thingengineering/wowthing/wowthing-web
          dockerfile: src/Wowthing.Web/Dockerfile
          tag_with_ref: true
          tag_with_sha: true

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save Kubernetes config
        run: doctl kubernetes cluster kubeconfig save thing

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) echo $TAG && sed -i "s/_VERSION_/${TAG}/" $GITHUB_WORKSPACE/.k8s/web-deployment.yml

      - name: Sigh
        run: cat $GITHUB_WORKSPACE/.k8s/web-deployment.yml

      - name: Deploy to Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/.k8s/web-deployment.yml

      - name: Verify deployment
        run: kubectl -n things rollout status deployment/wowthing-again
